/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ["var(--font-display)"],
        body: ["var(--font-body)"],
        displayEn: ['"Playfair Display"', "Georgia", "serif"],
        bodyEn: ['"Inter"', "system-ui", "sans-serif"],
        displayZh: ['"PingFang SC"', '"Hiragino Sans GB"', '"Noto Sans SC"', '"Microsoft YaHei"', "sans-serif"],
        bodyZh: ['"PingFang SC"', '"Hiragino Sans GB"', '"Noto Sans SC"', '"Microsoft YaHei"', "sans-serif"],
        "lab-headline": ['"Noto Serif"', "serif"],
        "lab-body": ["Manrope", "sans-serif"],
        "lab-label": ['"Space Grotesk"', "sans-serif"],
        headline: ['"Noto Serif"', "serif"],
        label: ["Inter", "sans-serif"],
      },
      colors: {
        background: "rgb(var(--site-bg-rgb) / <alpha-value>)",
        "on-background": "rgb(var(--site-text-rgb) / <alpha-value>)",
        surface: "rgb(var(--site-bg-deep-rgb) / <alpha-value>)",
        "surface-soft": "rgb(var(--site-bg-soft-rgb) / <alpha-value>)",
        "on-surface": "rgb(var(--site-text-rgb) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--site-muted-rgb) / <alpha-value>)",
        "surface-container-low": "rgb(var(--site-bg-elevated-rgb) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--site-bg-deep-rgb) / <alpha-value>)",
        "surface-container": "rgb(var(--site-bg-soft-rgb) / <alpha-value>)",
        "surface-bright": "rgb(var(--site-panel-strong-rgb) / <alpha-value>)",
        "surface-variant": "rgb(var(--site-muted-rgb) / 0.24)",
        outline: "rgb(var(--site-border-rgb) / <alpha-value>)",
        "outline-variant": "rgb(var(--site-border-soft-rgb) / <alpha-value>)",
        accent: "rgb(var(--site-accent-rgb) / <alpha-value>)",
        "accent-strong": "rgb(var(--site-accent-strong-rgb) / <alpha-value>)",
        foreground: "rgb(var(--site-text-rgb) / <alpha-value>)",
        muted: "rgb(var(--site-muted-rgb) / <alpha-value>)",
        "muted-strong": "rgb(var(--site-muted-strong-rgb) / <alpha-value>)",
        primary: "rgb(var(--site-accent-rgb) / <alpha-value>)",
        "on-primary": "var(--site-ink-on-accent)",
      },
      boxShadow: {
        soft: "0 28px 80px rgba(0, 0, 0, 0.32)",
      },
    },
  },
  plugins: [],
};
